language: node_js
node_js:
  - 'node'
script:
  - yarn build
  - yarn test:coveralls

# if using Ubuntu 16 need this library
# https://github.com/cypress-io/cypress-documentation/pull/1647
addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  # cache both npm modules and Cypress binary
  directories:
    - ~/.npm
    - ~/.cache

defaults: &defaults
  script:
    - npm run cy:test
    - npm run report:text
    - npm run coveralls
    - kill $(jobs -p) || true

jobs:
  include:
    - stage: test
      env:
        - STAGE_NAME="1x-electron on Travis CI"
      <<: *defaults
# # see https://github.com/cypress-io/circleci-orb
# version: 2.1
# orbs:
#   cypress: cypress-io/cypress@1
# workflows:
#   build:
#     jobs:
#       - cypress/run:
#           # we need to start the web application
#           start: npm start
#           command: NODE_ENV=test npm run cypress:run
#           # there are no jobs to follow this one
#           # so no need to save the workspace files (saves time)
#           no-workspace: true
#           post-steps:
#             # store the created coverage report folder
#             # you can click on it in the CircleCI UI
#             # to see live static HTML site
#             - store_artifacts:
#                 path: coverage
#             # show code coverage numbers
#             - run: npm run report:coverage:text
#             # send code coverage to coveralls.io
#             # https://coveralls.io/github/cypress-io/cypress-example-todomvc-redux
#             - run: npm run coveralls
